export const lightTheme = {
  colors: {
    background: {
      white: 'var(--white)',
      primary: 'var(--blue-500)',
      primaryPressed: 'var(--blue-600)',
      secondary: 'var(--gray-100)',
      secondaryPressed: 'var(--gray-300)',
      tertiary: 'var(--gray-800)',
      tertiaryPressed: 'var(--gray-900)',
      weak: 'var(--blue-100)',
      table: 'var(--blue-200)',
      error: 'var(--red-500)',
      opacityWhite: '#ffffff90',
      opacityBlack: '#00000050',
      opacityGray: '#41424450',
    },
    border: {
      primary: 'var(--gray-300)',
      primaryPressed: 'var(--gray-400)',
      secondary: 'var(--gray-700)',
      tertiary: 'var(--blue-500)',
      text: 'var(--gray-500)',
      error: 'var(--red-500)',
    },
    divider: {
      primary: 'var(--gray-200)',
      error: 'var(--red-500)',
    },
    icon: {
      white: 'var(--white)',
      primary: 'var(--gray-800)',
      secondary: 'var(--gray-500)',
      tertiary: 'var(--gray-300)',
      notice: 'var(--blue-500)',
      error: 'var(--red-500)',
    },
    typo: {
      white: 'var(--white)',
      primary: 'var(--gray-900)',
      secondary: 'var(--gray-700)',
      tertiary: 'var(--gray-500)',
      weak: 'var(--gray-400)',
      disabled: 'var(--gray-500)',
      true: 'var(--blue-500)',
      error: 'var(--red-500)',
    },
  },
};
