name: Deploy

on:
  pull_request:
    branches: ['dev', 'main']
  push:
    branches: ['dev', 'main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Install mustache (to update the date)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          sudo gem install mustache
      - name: creates output
        run: sh ./build.sh

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: AhnRian
          destination-repository-name: front
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.head_commit.message }}
          target-branch: ${{ github.ref_name }}

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
